dist: trusty
language: node_js
node_js:
  - "6"
  - "6.1"
  - "7"
script:
  - cd dist && npm install && cd ..
  - npm test
  - npm run quality
  - npm run dist
  - npm run build-linux
  - npm run release-linux